version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3001
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    container_name: api-resume-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:
