name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/home/deployuser/app"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PORT=${{ secrets.PORT }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_MAX=${{ secrets.POSTGRES_MAX }}
            POSTGRES_IDLE_TIMEOUT=${{ secrets.POSTGRES_IDLE_TIMEOUT }}
            POSTGRES_CONNECTION_TIMEOUT=${{ secrets.POSTGRES_CONNECTION_TIMEOUT }}
            cd /home/deployuser/app
            docker-compose down
            docker-compose up -d
