name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # or any branch you want to deploy from
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/app"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export PORT=${{ secrets.PORT }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            export POSTGRES_MAX=${{ secrets.POSTGRES_MAX }}
            export POSTGRES_IDLE_TIMEOUT=${{ secrets.POSTGRES_IDLE_TIMEOUT }}
            export POSTGRES_CONNECTION_TIMEOUT=${{ secrets.POSTGRES_CONNECTION_TIMEOUT }}
            cd /home/${{ secrets.SERVER_USER }}/app
            docker compose down
            docker compose build --no-cache
            docker compose up -d
